# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('calendario', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Timbre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='polls/timbres')),
                ('nombre_timbre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=200)),
                ('primer_apellido', models.CharField(max_length=200)),
                ('segundo_apellido', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='alarma',
            name='timbre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Timbre'),
        ),
        migrations.AddField(
            model_name='alarma',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Usuario'),
        ),
    ]
