# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarma',
            name='nombre_alarma',
            field=models.CharField(default='', max_length=200),
        ),
    ]
