# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='segundo_apellido',
        ),
    ]
